auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("new_listings", views.new_listings, name="new_listings"),
    path("bid/<int:pk>", views.bid, name="bid"),
    path("categories", views.categories, name="categories"),
    path("ActiveAuctions", views.ActiveAuctions, name="ActiveAuctions"),
    path("DeActiveAuctions", views.DeActiveAuctions, name="DeActiveAuctions"),    
    path("per_category/<int:pk>", views.per_category, name="per_category"),
    path("Edit_auction/<int:pk>", views.Edit_auction, name="Edit_auction"),
    path("AuctionPerUser", views.AuctionPerUser, name="AuctionPerUser"),
    path("Add_watchlist/<int:pk>", views.Add_watchlist, name="Add_watchlist"),    
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.db.models.fields import CharField
from django.db.models.fields.related import ForeignKey


class User(AbstractUser):
    pass

class Category(models.Model):
    category = CharField(max_length=50, null=False)

class listings(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE, null=False, default='1')
    title = models.CharField(max_length=50 , null=False, unique=True)
    description = models.CharField(max_length=100, null=False, default='ABC')
    starting_price = models.IntegerField(null=False , default='123')
    category = models.ForeignKey(Category, on_delete=CASCADE, null=False, default='1')
    active = models.BooleanField(null=False, default=False)


class Bids(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE, null=False, default='1')
    auction = models.ForeignKey(listings, on_delete=CASCADE, null=False, default='1')
    bid_price = models.IntegerField(null=False, default='1000')
    bid_time = models.TimeField(null=False, default='00:00:00')

class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE, null=False, default='1')
    auction = models.ForeignKey(listings, on_delete=CASCADE, null=False, default='1')
    comments = models.CharField(max_length=150, default='abc')

class watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE,)
    auction = models.ForeignKey(listings, on_delete=CASCADE)
    active = models.BooleanField(default=False)

auctions/views.py
import auctions
from datetime import datetime

from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse


from .models import Bids, Category, Comments, User, listings, watchlist


def index(request):
        auction_list = listings.objects.filter(active=1)
        return render(request, "auctions/index.html",{
            'auction_list' : auction_list
            })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

def new_listings(request):
    if request.method == "POST":
        try:
            title = request.POST["title"]
            Description = request.POST["Description"]
            price = request.POST["price"]
            cat = request.POST["cat"]
            active = request.POST.get("active")
            if active is None:
                active = 0

            category = Category.objects.get(id=cat)

            new_list = listings.objects.create(user=request.user,title=title,description=Description, starting_price=price, category=category, active=active)
            new_list.save()
            return HttpResponseRedirect(reverse("index"))

        except IntegrityError:
            category = Category.objects.all().order_by('category')
            return render(request, "auctions/new_listings.html", {
                "message": "Item already taken.",
                'category' : category
            })
        except Exception as e:
            category = Category.objects.all().order_by('category')
            return render(request, "auctions/new_listings.html", {
                "message": str(e),
                'category' : category
            })
    else:
        category = Category.objects.all().order_by('category')
        return render(request, "auctions/new_listings.html",{
            'category' : category
        })

def bid(request, pk):

    if request.method == "POST":
        try:
            bid_price = request.POST["bid"]
            comment = request.POST["comment"]
            time = datetime.now()
        
            Bids.objects.create(user=request.user, bid_price=bid_price, auction_id=pk, bid_time=time)
            Comments.objects.create(user=request.user, comments=comment, auction_id=pk)

            return redirect(index)
        except Exception as e:
            auction_list = listings.objects.get(id=pk)
            category = Category.objects.get(id=auction_list.category_id)
            bids_list = Bids.objects.filter(auction_id=pk)
            return render(request, "auctions/bid.html", {
                "message": str(e),
                'id' : pk,
                'auction_list' : auction_list,
                'category' : category,
                'bids_list' : bids_list
            })
    else:
        auction_list = listings.objects.get(id=pk)
        category = Category.objects.get(id=auction_list.category_id)
        bids_list = Bids.objects.filter(auction_id=pk)
        return render(request, "auctions/bid.html", {
            'id' : pk,
            'auction_list' : auction_list,
            'category' : category,
            'bids_list' : bids_list
            })

def categories(request):
        cat_list = Category.objects.all()
        return render(request, "auctions/categories.html",{
            'cat_list' : cat_list           
            })

def per_category(request, pk):
        auction_list = listings.objects.filter(category_id=pk)
        return render(request, "auctions/per_category.html", 
            {'id' : pk, 'auction_list' : auction_list}
        )

def ActiveAuctions(request):
        Active_list = listings.objects.filter(user_id=request.user.id, active=1)
        return render(request, "auctions/ActiveAuctions.html", {'Active_list' : Active_list})

def DeActiveAuctions(request):
        De_Active_list = listings.objects.filter(user_id=request.user.id, active=0)
        return render(request, "auctions/DeActiveAuctions.html", {'De_Active_list' : De_Active_list})

def Edit_auction(request, pk):
    if request.method == "POST":
        try:
            title = request.POST["title"]
            Description = request.POST["Description"]
            price = request.POST["price"]
            cat = request.POST["cat"]
            active = request.POST.get("active")
            if active is None:
                active = 0

            category = Category.objects.get(id=cat)

            update_list = listings.objects.filter(id=pk).update(user=request.user,title=title,description=Description, starting_price=price, category=category, active=active)
            return HttpResponseRedirect(reverse("AuctionPerUser"))

        except Exception as e:
            category = Category.objects.all().order_by('category')
            return render(request, "auctions/new_listings.html", {
                "message": str(e),
                'category' : category
            })
    else:
        category = Category.objects.all().order_by('category')
        auction_item = listings.objects.get(id=pk)
        return render(request, "auctions/Edit_auction.html",{
            'category' : category,
            'pk' : pk,
            'auction_item' : auction_item
        })

def AuctionPerUser(request):
    all_acution_list = listings.objects.filter(user_id=request.user.id)
    return render(request, "auctions/AuctionPerUser.html",{
        'all_acution_list' : all_acution_list
    })

def Add_watchlist(request,pk):
    if request.method == "POST":
        active = 1
        add = watchlist.objects.create(user_id=request.user.id,auction_id=pk,active=active)
        print(add)
        return redirect(index)
    else:
        print("not add")
        return redirect(index)





    

auctions/templates/auctions/ActiveAuctions.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listing of Your Auctions</h2>
    <div class="row">
        {% for Active_item in Active_list %}
                <div class="col-sm-4">
                    <div class="card text-dark border-primary">
                        <h5 class="card-header">{{ Active_item.title }}</h5>
                        <div class="card-body">
                            <p class="card-subtitle mb-2 text-muted">Category : {{ Active_item.category.category }}</p>
                            <p class="card-text">Description : {{ Active_item.description }}</p>
                            <p class="card-text">Price : {{ Active_item.starting_price }}</p>
                            <div class="card-footer bg-transparent border-success">
                            <a href="{% url 'Edit_auction' pk=Active_item.id %}" class="btn btn-primary col-12">Edit Your Auction</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/Add_watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Your Watch List</h2>
<div class="row">
    <form action="{% url 'Add_watchlist' pk=id %}" method="post">
        <input class="btn btn-primary col-12" type="submit" value="Send">
    </form>
</div>
{% endblock %}

auctions/templates/auctions/AuctionPerUser.html
{% extends "auctions/layout.html" %}

{% block body %}
{% if message %}
<div class="alert alert-success">{{ message }}</div>
{% endif %}
    <h2>All of Your Auctions</h2>
    <div class="row">
        {% for all_acution_item in all_acution_list %}
                <div class="col-sm-4">
                    <div class="card text-dark border-primary">
                        <h5 class="card-header">{{ all_acution_item.title }}</h5>
                        <div class="card-body">
                            <p class="card-subtitle mb-2 text-muted">Category : {{ all_acution_item.category.category }}</p>
                            <p class="card-text">Description : {{ all_acution_item.description }}</p>
                            <p class="card-text">Price : {{ all_acution_item.starting_price }}</p>
                            <div class="card-footer bg-transparent border-success">
                            <a href="{% url 'Edit_auction' pk=all_acution_item.id%}" class="btn btn-primary col-12">Edit Your Auction</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/DeActiveAuctions.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>De-Activeted Listing of Your Auctions</h2>
    <div class="row">
        {% for De_Active_item in De_Active_list %}
                <div class="col-sm-4">
                    <div class="card text-dark border-primary">
                        <h5 class="card-header">{{ De_Active_item.title }}</h5>
                        <div class="card-body">
                            <p class="card-subtitle mb-2 text-muted">Category : {{ De_Active_item.category.category }}</p>
                            <p class="card-text">Description : {{ De_Active_item.description }}</p>
                            <p class="card-text">Price : {{ De_Active_item.starting_price }}</p>
                            <div class="card-footer bg-transparent border-success">
                            <a href="{% url 'Edit_auction' pk=De_Active_item.id%}" class="btn btn-primary col-12">Edit Your Auction</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/Edit_auction.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2 style="text-align: center;">Edit Auction</h2>
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <div class="row">
        <div class="col-sm-4 offset-4">
            <div class="card text-dark">
                <form action="{% url 'Edit_auction' pk=pk %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input autofocus value="{{auction_item.title}}" class="form-control" type="text" name="title" placeholder="Title">
                    </div>
                    <div class="form-group">
                        <input class="form-control" value="{{auction_item.description}}" type="text" name="Description" placeholder="Description">
                    </div>
                    <div class="form-group">
                        <input class="form-control" value="{{auction_item.starting_price}}" type="text" name="price" placeholder="Starting Price For BID">
                    </div>
                    <div class="form-group">
                        <select name="cat">
                        {% for cat in category %}
                        <option value="{{cat.id}}">{{ cat.category }}</option>
                        {% endfor %}
                        </select>
                        <label class="form-label offset-1">&nbsp;&nbsp;Previous Category : {{ auction_item.category.category }}</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" name="active" type="checkbox" value="1" id="Active">
                        <label class="form-check-label" for="Active">
                            Active
                        </label>
                        <label class="form-label offset-3">Previous Active Stutas : {{ auction_item.active }}</label>
                    </div>
                    <input class="btn btn-primary" type="submit" value="Update Auction">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

auctions/templates/auctions/bid.html
{% extends "auctions/layout.html" %}

{% block body %}
    {% if message %}
    <div class="alert alert-primary">{{ message }}</div>
    {% endif %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <div class="card text-dark border-primary">
                <h5 class="card-header">{{ auction_list.title }}</h5>
                <div class="card-body">
                    <p class="card-subtitle mb-2 text-muted">Category : {{ auction_list.category.category }}</p>
                    <p class="card-text">Description : {{ auction_list.description }}</p>
                    <p class="card-text">Price : {{ auction_list.starting_price }}</p>
                    {% if user.is_authenticated %}
                    <form action="{% url 'bid' pk=id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input autofocus class="form-control" type="text" name="bid" placeholder="BID Price">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="comment" placeholder="Comments">
                    </div>
                    <div class="card-footer bg-transparent border-success">
                        <input class="btn btn-primary col-12" type="submit" value="Send">
                    </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div style="position: absolute; float: right; font-size: 20px;">
                <h1 class="heading-style">Previous Bids</h1>
                <ol>
                <strong>Your Bids:</strong>
                    {% for bid_item in bids_list %}
                    {% if request.user.id == bid_item.user.id %}
                        <li><strong>Price</strong> : {{ bid_item.bid_price }},
                            <strong>Time</strong>  : {{ bid_item.bid_time}},
                            <strong>User</strong> : {{ bid_item.user.username }}
                        </li>
                    {% endif %}
                    {% empty %}
                    <li>Sorry, no Bids for this Auction.</li>
                    {% endfor %}
                </ol>
                <ol>
                    <strong>Other's Bids:</strong>
                    {% for bid_item in bids_list %}
                    {% if request.user.id != bid_item.user.id %}
                        <li><strong>Price</strong> : {{ bid_item.bid_price }},
                            <strong>Time</strong>  : {{ bid_item.bid_time}},
                            <strong>User</strong> : {{ bid_item.user.username }}
                        </li>
                    {% endif %}
                    {% empty %}
                    <li>Sorry, no Bids in this Auction.</li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    {% else %}
    Please Login For BID
    {% endif %}
    </div>
</div>
{% endblock %}

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Categories</h2>

    {% for cat_item in cat_list %}
    <ol class="list-group list-group">
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
                <div class="fw-bold">
                    <a href="{% url 'per_category' pk=cat_item.id %}">{{ cat_item.category }}</a>
                        <span class="badge bg-danger rounded-pill">{{ cat_item.listings_set.count }}</span>
                </div>
            </div>
        </li>
    </ol>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
{% if message %}
    <div class="alert alert-success">{{ message }}</div>
{% endif %}
    <div class="row">
        {% for auction_item in auction_list %}
                <div class="col-sm-4">
                    <div class="card text-dark border-primary">
                        <h5 class="card-header">{{ auction_item.title }}</h5>
                        <div class="card-body">
                            <p class="card-subtitle mb-2 text-muted">Category : {{ auction_item.category.category }}</p>
                            <p class="card-text">Description : {{ auction_item.description }}</p>
                            <p class="card-text">Price : {{ auction_item.starting_price }}</p>

                            <div class="card-footer bg-transparent border-success">
                                <div class="row">
                                <a href="{% url 'bid' pk=auction_item.id %}" class="btn btn-info col-4">Bid Now!</a>
                                <a href="{% url 'Add_watchlist' pk=auction_item.id %}" class="btn btn-success offset-4 col-4">
                                    Add
                                </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        
        <title>{% block title %}Auctions{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        <div class="row">
            <div class="col">
                <img  class="img-fluid" src="{% static 'images/logo.png' %}" alt="LOGO">
            </div>
            <div class="col">
                {% if user.is_authenticated %}
                    <h5 style="text-align: right; padding-top: 10%;">Signed in as <strong>{{ user.username|capfirst }}</strong>.</h5>
                {% else %}
                <h5 style="text-align: right; padding-top: 10%;">Not signed in.</h5>
                {% endif %}
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'index' %}">Auctions</a>
            <div class="collapse navbar-collapse" id="main_nav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'categories' %}">Categories</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">

                       
                    </li>
                    <li class="nav-item">
                        <span class="badge bg-danger rounded-pill">23</span>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">Your Auctions</a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" href="{% url 'AuctionPerUser' %}">Your All Auctions</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'ActiveAuctions' %}">Your Active Auctions</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'DeActiveAuctions' %}">Your De-Activeted Auctions</a>
                                </li>
                            </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'new_listings' %}">Create New Listings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            </div>
        </nav>
        <hr>
        {% block body %}
        
        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}
  <h2 style="text-align: center;">Login</h2>

  {% if message %}
  <div class="alert alert-primary">{{ message }}</div>
  {% endif %}
  <div class="row">
    <div class="col-sm-4 offset-4">
      <div class="card text-dark">
        <form action="{% url 'login' %}" method="post">
          {% csrf_token %}
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            <input class="form-control" type="password" name="password" placeholder="Password">
          <input class="btn btn-primary" type="submit" value="Login">
        </form>
        Don't have an account? <a href="{% url 'register' %}">Register here.</a>
      </div>
    </div>
  </div>
{% endblock %}

auctions/templates/auctions/new_listings.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2 style="text-align: center;">Create New Listings</h2>
    {% if message %}
    <div class="alert alert-primary">{{ message }}</div>
    {% endif %}
    <div class="row">
        <div class="col-sm-4 offset-4">
            <div class="card text-dark">
                <form action="{% url 'new_listings' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input autofocus class="form-control" type="text" name="title" placeholder="Title">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="Description" placeholder="Description">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="price" placeholder="Starting Price For BID">
                    </div>
                    <div class="form-group">
                        <select name="cat">
                        {% for cat in category %}
                        <option value="{{cat.id}}">{{ cat.category }}</option>
                        {% endfor %}
                        </select>
                    <div class="form-check offset-10">
                        <input class="form-check-input" name="active" type="checkbox" value="1" id="Active">
                        <label class="form-check-label" for="Active">
                            Active
                        </label>
                        </div>
                    </div>
                    <input class="btn btn-primary" type="submit" value="Place Auction">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

auctions/templates/auctions/per_category.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings Per Category</h2>
    <div class="row">
        {% for auction_item in auction_list %}
                <div class="col-sm-4">
                    <div class="card text-dark border-primary">
                        <h5 class="card-header">{{ auction_item.title }}</h5>
                        <div class="card-body">
                            <p class="card-subtitle mb-2 text-muted">Category : {{ auction_item.category.category }}</p>
                            <p class="card-text">Description : {{ auction_item.description }}</p>
                            <p class="card-text">Price : {{ auction_item.starting_price }}</p>
                            <div class="card-footer bg-transparent border-success">
                            <a href="{% url 'bid' pk=auction_item.id %}" class="btn btn-primary col-6">Bid Now!</a>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2 style="text-align: center;">Register</h2>

    {% if message %}
    <div class="alert alert-primary">{{ message }}</div>
    {% endif %}
    <div class="row">
        <div class="col-sm-4 offset-4">
          <div class="card text-dark">
                <form action="{% url 'register' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" autofocus type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="email" name="email" placeholder="Email Address">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Register">
                </form>
                    Already have an account? <a href="{% url 'login' %}">Log In here.</a>
            </div>
        </div>
    </div>
{% endblock %}